spring:
  application:
    name: centinela-generator

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

centinela:
  generator:
    mode: ${GENERATOR_MODE:idle}
    transactions-per-second: ${GENERATOR_TPS:10}
    accounts: ${GENERATOR_ACCOUNTS:200}
  kafka:
    topics:
      transactions: ${KAFKA_TOPIC_TRANSACTIONS:spei.transactions}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
